select * from [TABELA DE PRODUTOS]

INSERT INTO [TABELA DE PRODUTOS] 
([CODIGO DO PRODUTO], [NOME DO PRODUTO],EMBALAGEM,SABOR,[PRECO DE LISTA]) VALUES 
('125145','Lavanda Tropical - 1000ml - Tangerina', 'Garrafa', 'Tangerina',75.68)

DELETE FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '000000'

-- ADICIONAR UMA CONSTRAINT 
-- ALTERAR TABALA   ADICIONAR ALGO NO CASO UMA CONSTAINT  NOME E TIPO      (AS COLUNAS QUE SÃO PRIMARY KEY)
ALTER TABLE [TABELA DE PRODUTOS] ADD CONSTRAINT PK_TABELA_DE_PRODUTO PRIMARY KEY CLUSTERED ([CODIGO DO PRODUTO])

-- CAMPOS NULOS
INSERT INTO [TABELA DE PRODUTOS] 
([CODIGO DO PRODUTO], [NOME DO PRODUTO],EMBALAGEM,SABOR,[PRECO DE LISTA]) VALUES 
('123456','Lavanda Tropical - 1000ml - Tangerina', NULL, 'Tangerina',75.68)

select * from [TABELA DE PRODUTOS]
-- SELECIONAR CAMPO NULO = IS NULL
SELECT [CODIGO DO PRODUTO] FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] IS NULL
SELECT *FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] IS NULL

DELETE [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] IS NULL

-- ALTERAR COLUNA PARA NÃO ACEITAR NULO

ALTER TABLE [TABELA DE PRODUTOS]
ALTER COLUMN [CODIGO DO PRODUTO] VARCHAR(20) NOT NULL

-- TENTAR INSERIR CODIGO DO PRODUTO NULO
SELECT * FROM [TABELA DE PRODUTOS]

INSERT INTO [TABELA DE PRODUTOS]
VALUES (NULL,'SUCO DE LARANJA E ABACAXI','PET','LARANJA',10.50)

-- INSERINDO PRIMARY KEY

ALTER TABLE [TABELA DE PRODUTOS] ADD CONSTRAINT PK_TABELA_DE_PRODUTOS PRIMARY KEY CLUSTERED ([CODIGO DO PRODUTO])

