SELECT *FROM [TABELA DE VENDEDORES]

ALTER TABLE [TABELA DE VENDEDORES]
ALTER COLUMN [MATRICULA] VARCHAR (5) NOT NULL

ALTER TABLE [TABELA DE VENDEDORES]
ADD CONSTRAINT PK_TABELA_DE_VENDEDORES PRIMARY KEY CLUSTERED (MATRICULA)
--EXCLUIR LINHA
DELETE FROM [TABELA DE VENDEDORES] WHERE MATRICULA = '00239'
-- ADICIONAR COLUNA
ALTER TABLE [TABELA DE VENDEDORES]
ADD APELIDO VARCHAR (20)
-- EXCLUIR COLUNA
ALTER TABLE [TABELA DE VENDEDORES]
DROP COLUMN APELIDO

ALTER TABLE [TABELA DE VENDEDORES]
ALTER COLUMN [PERCENTUAL COMISSAO] FLOAT NOT NULL

