SELECT * FROM [TABELA DE PRODUTOS] WHERE SABOR = 'Manga' OR TAMANHO > '700 ml'
SELECT * FROM [TABELA DE PRODUTOS] WHERE SABOR = 'Manga' AND TAMANHO = '700 ml'


-- NEGAÇÃO DA EXPRESSÃO OU SEJA SABOR E TAMANHO DIFERENTE DA CONDICIONAL

SELECT * FROM [TABELA DE PRODUTOS] WHERE NOT(SABOR = 'Manga' AND TAMANHO = '700 ml')

--condicional in e de inclusão manga e laranja semelhante ao or
SELECT * FROM [TABELA DE PRODUTOS] WHERE SABOR IN('Manga','Laranja')

SELECT * FROM [TABELA DE PRODUTOS] WHERE SABOR NOT IN('Manga','Laranja')
-- BETWEEN E = ENTRE
SELECT * FROM [TABELA DE PRODUTOS] WHERE SABOR IN ('Cereja', 'Limão') AND [PRECO DE LISTA] BETWEEN 8 AND 12