/*CRIAR BANCO DE DADOS*/
/**/
CREATE DATABASE SUCOS_VENDAS_01 ON 
(	NAME = 'SUCOS_VENDAS.DAT',
	FILENAME = 'C:\estudoSQL\SALES_VENDAS_02.MDF',
	SIZE = 10MB,
	MAXSIZE = 50MB,
	FILEGROWTH = 5MB
)
LOG ON
(	NAME = 'SUCOS_VENDAS.LOG',
	FILENAME = 'C:\estudoSQL\SALES_VENDAS_02.LDF',
	SIZE = 10MB,
	MAXSIZE = 50MB,
	FILEGROWTH = 5MB
)

/*LEGENDA
NAME = NOME DO BANCO
FILENAME = CAMINHO DO BANCO E NOME
SIZE = TAMANHO INICIAL DO BANCO
MAXSIZE = O MAXIMO QUE O BANCO VAI CRESCER
FILEGROWTH = DE QUANTO E QUANTO MEGAS O BANCO VAI CRESCER
*/