--LIKE => PECORRE A STRING E BUSCA A PALAVRA
-- LIKE '%SOARES%' = EM QUALQUER OCORRENCIA DA STRING
-- LIKE '%SOARES' = APENAS NO FINAL
-- LIKE 'SOARES%' = 

SELECT * FROM [TABELA DE PRODUTOS] WHERE [NOME DO PRODUTO] LIKE '%Litros%'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [NOME DO PRODUTO] LIKE '%Limão' -- que termina com a palavra Limão

SELECT * FROM [TABELA DE PRODUTOS] WHERE [NOME DO PRODUTO] LIKE 'Linha%' -- que começa com a palavra linha

SELECT * FROM [TABELA DE PRODUTOS] WHERE [NOME DO PRODUTO] LIKE '%Limão' AND SABOR = 'Limão'

-- DISTINCT MOSTRA AS LINHAS DOS PRODUTOS NA TABELA QUE NÃO SE REPETE SE REPETIR ELE MOSTRA APENAS UM REGISTRO

SELECT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO,SABOR FROM [TABELA DE PRODUTOS] WHERE SABOR = 'Laranja'

-- OS TRES PRIMEIROS REGISTRO DA CONDIÇÃO
SELECT TOP 3 * FROM [TABELA DE PRODUTOS]

--SELECIONAR VALORES DOS CAMPOS NÃO IGUAL NA LINHA OS TRES PRIMEIROS DE SABOR LARANJA OU LIMÃO
SELECT DISTINCT TOP 5 * FROM [TABELA DE PRODUTOS] WHERE SABOR IN ('Laranja','Limão')