--INSERIR REGISTRO UNICO NA TABELA PRODUTO

select * from [TABELA DE PRODUTOS]

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],
[NOME DO PRODUTO],
EMBALAGEM,
SABOR,[PRECO DE LISTA])
VALUES
('812829','Clean - 350 ml - Laranja','LATA','LARANJA',2.81)

-- INSERIR REGISTRO UNICO NA TABELA VENDEDORES
SELECT * FROM [TABELA DE VENDEDORES]

INSERT INTO [TABELA DE VENDEDORES]
(MATRICULA,NOME,[PERCENTUAL COMISSAO]) VALUES
('00236','Cláudia Morais',0.15)

--INSERIR VARIO VALORES EM UM INSERT

INSERT INTO [TABELA DE PRODUTOS] (
[CODIGO DO PRODUTO],
[NOME DO PRODUTO],
EMBALAGEM,
SABOR,
[PRECO DE LISTA]) 
VALUES
('290478','Videira do Campo - 350 ml - Melância','Lata','Melância',4.56),
('783663','Sabor da Montanha - 700 ml - Morango','Garrafa','Morango',7.71)

-- UPDATE TABELA VENDEDORES CORRIGINDO CAMPOS

SELECT * FROM [TABELA DE VENDEDORES]
UPDATE [TABELA DE VENDEDORES]
SET NOME = 'Cláudia Morais Sousa', [PERCENTUAL COMISSAO] = 0.11 WHERE MATRICULA = '00236'

--UPDATE [TABELA] SET [CAMPO] = VALOR, [OUTRO CAMPO] = VALOR ONDE [CAMPO] = VALOR
-- INSERT EM [TABELA] ([CAMPO 1], [CAMPO 2] ....) VALUES('CAMPO 1', CAMPO 2), ('OUTRA LINHA CAMPO 1', NUMERO CAMPO 2
-- DROP TABLE [TABELA]

--FAZENDO UPDATE TABELA PRODUTO

SELECT * FROM [TABELA DE PRODUTOS]

UPDATE [TABELA DE PRODUTOS] SET SABOR = 'Maracujá', [PRECO DE LISTA] = 4.91 WHERE [CODIGO DO PRODUTO] = '723457'

--DELETANDO LINHA DA TABELA PRODUTO

DELETE [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] =	'812829'

-- INSERIRNDO
INSERT INTO [TABELA DE VENDEDORES]
([NOME], 
[MATRICULA],
[PERCENTUAL COMISSAO])
VALUES
('Alberto de Sá Verneck','00239',0.08);