--EXPLICAÇÃO DEFINITIVA DOS JOINS
SELECT * FROM [TABELA DE VENDEDORES]
SELECT * FROM [TABELA DE CLIENTES]

ALTER TABLE [TABELA DE VENDEDORES] ADD BAIRRO VARCHAR(50) NULL

UPDATE [TABELA DE VENDEDORES] SET BAIRRO = 'Copacabana' WHERE MATRICULA = '00238'
--VALUES ('Tijuca'), ('Jardins'), ('Santo Amaro'), ('Copacabana')

SELECT [TABELA DE VENDEDORES].NOME AS [VENDEDORES],[TABELA DE VENDEDORES].BAIRRO, 
[TABELA DE CLIENTES].NOME AS [CLIENTES],[TABELA DE CLIENTES].BAIRRO
FROM [TABELA DE VENDEDORES] INNER JOIN [TABELA DE CLIENTES] ON
[TABELA DE VENDEDORES].BAIRRO = [TABELA DE CLIENTES].BAIRRO

SELECT [TABELA DE VENDEDORES].NOME AS [VENDEDORES],[TABELA DE VENDEDORES].BAIRRO, 
[TABELA DE CLIENTES].NOME AS [CLIENTES],[TABELA DE CLIENTES].BAIRRO
FROM [TABELA DE VENDEDORES] LEFT JOIN [TABELA DE CLIENTES] ON
[TABELA DE VENDEDORES].BAIRRO = [TABELA DE CLIENTES].BAIRRO


SELECT [TABELA DE VENDEDORES].NOME AS [VENDEDORES],[TABELA DE VENDEDORES].BAIRRO, 
[TABELA DE CLIENTES].NOME AS [CLIENTES],[TABELA DE CLIENTES].BAIRRO
FROM [TABELA DE VENDEDORES] RIGHT JOIN [TABELA DE CLIENTES] ON
[TABELA DE VENDEDORES].BAIRRO = [TABELA DE CLIENTES].BAIRRO

SELECT [TABELA DE VENDEDORES].NOME AS [VENDEDORES],[TABELA DE VENDEDORES].BAIRRO, 
[TABELA DE CLIENTES].NOME AS [CLIENTES],[TABELA DE CLIENTES].BAIRRO
FROM [TABELA DE VENDEDORES] FULL JOIN [TABELA DE CLIENTES] ON
[TABELA DE VENDEDORES].BAIRRO = [TABELA DE CLIENTES].BAIRRO

SELECT [TABELA DE VENDEDORES].NOME AS [VENDEDORES],[TABELA DE VENDEDORES].BAIRRO, 
[TABELA DE CLIENTES].NOME AS [CLIENTES],[TABELA DE CLIENTES].BAIRRO
FROM [TABELA DE VENDEDORES] CROSS JOIN [TABELA DE CLIENTES] ON
[TABELA DE VENDEDORES].BAIRRO = [TABELA DE CLIENTES].BAIRRO