SELECT * FROM [TABELA DE CLIENTES]

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] >= '2000-03-12'
-- SELEÇÃO PELO ANO
SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) > 1995
-- SELEÇÃO PELO MES
SELECT * FROM [TABELA DE CLIENTES] WHERE MONTH([DATA DE NASCIMENTO]) = 11

SELECT * FROM [TABELA DE CLIENTES] WHERE DAY([DATA DE NASCIMENTO]) = 12

SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) >= 1995 AND SEXO = 'F'
-- OR = OU
SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) <= 1995 
AND SEXO = 'M' AND ESTADO = 'SP' OR ESTADO = 'RJ'