SELECT * FROM [TABELA DE CLIENTES] WHERE CIDADE = 'Rio de Janeiro' ORDER BY BAIRRO
-- AS FUNÇOS DE SOMA, MINIMO,MAXIMO, MEDIA E COUNT SO FUNCIONA COM A IMPLEMENTAÇÃO DO GROUP BY

-- GROUP BY ORDENA EM ORDEM ALFABETICA MAS PRECISA DE UM PARAMETRO DO SELECT PARA FUNCIONAR
SELECT CIDADE, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY CIDADE

-- SEM PARAMETRO ELE SOMA TUDO QUE TEM NA COLUNA
SELECT SUM([LIMITE DE CREDITO])  FROM [TABELA DE CLIENTES]

--SOMA O LIMITE DE CREDITO DE CADA ESTADO NA TABELA CLIENTE E ORDENA EM ORDER DECRESCENTE
SELECT ESTADO, SUM([LIMITE DE CREDITO]) AS [LIMITE DE CREDITO TOTAL] FROM [TABELA DE CLIENTES] GROUP BY ESTADO ORDER BY ESTADO DESC

-- A MEDIA DO LIMITE DE CREDIDO DE CADA ESTADO
SELECT ESTADO, AVG([LIMITE DE CREDITO]) AS [LIMITE DE CREDITO MEDIA] FROM [TABELA DE CLIENTES] GROUP BY ESTADO

-- A EMBALAGEM MAIS CARA
SELECT EMBALAGEM, MAX([PRECO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

--EMBALAGEM MAIS BARATA
SELECT EMBALAGEM, MIN([PRECO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

--CONTA QUANTAS EMBALAGEM IGUAL TEM NA TABELA
SELECT EMBALAGEM, COUNT(*) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE ESTADO = 'SP' GROUP BY BAIRRO




SELECT * FROM [TABELA DE CLIENTES]
-- TUDO QUE ENTRA NO SELECT ENTRA TAMBEM NA CONDICIONAL E PRECISA ESTA NO GROUP BY
SELECT ESTADO,CIDADE, MIN([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE SEXO = 'M'  GROUP BY ESTADO, CIDADE