SELECT * FROM [NOTAS FISCAIS]
SELECT * FROM [TABELA DE VENDEDORES]

-- INNER JOIN

SELECT * FROM [TABELA DE VENDEDORES] INNER JOIN
[NOTAS FISCAIS] ON [TABELA DE VENDEDORES].MATRICULA = [NOTAS FISCAIS].MATRICULA

-- COLOCANDO UM ALIAS NO INNER JOIN SEM O COMANDO AS

SELECT * FROM [TABELA DE VENDEDORES] VENDEDORES INNER JOIN
[NOTAS FISCAIS] NOTAS ON VENDEDORES.MATRICULA = NOTAS.MATRICULA

-- FILTRAR NOTAS FISCAIS POR VENDEDORES

SELECT [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].NOME, 
COUNT(*) AS [NUMERO DE NOTAS FISCAIS POR NOME E MATRICULA]
FROM [TABELA DE VENDEDORES]
INNER JOIN [NOTAS FISCAIS] ON [TABELA DE VENDEDORES].MATRICULA = [NOTAS FISCAIS].MATRICULA
GROUP BY [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].NOME

--FILTRAR POR ANO E QUANTIDADE DE NOTAS
-- SELECT DA TABELA VENDEDORES O CAMPO MATRICULA E NOME, TABELA NOTAS A COLUNA DATA E CONTA QUANTOS ANOS REPETIDOS
-- E FILTRA AGRUPANDO NOME E MATRICULA DA TABELA DE VENDEDORES PELO RESULTADO DO COUNT AS DATAS REPETIDAS

SELECT [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].NOME, YEAR(DATA) AS [ANO DA TABELA NOTAS FISCAIS], 
COUNT(*) AS [NUMERO DE NOTAS POR ANO] 
FROM [TABELA DE VENDEDORES] INNER JOIN
[NOTAS FISCAIS] ON [TABELA DE VENDEDORES].MATRICULA = [NOTAS FISCAIS].MATRICULA 
GROUP BY [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].NOME, YEAR(DATA)

-- A MESMA QUERY COM O ORDER BY

SELECT [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].NOME, YEAR([NOTAS FISCAIS].DATA) AS [ANO DA TABELA NOTAS FISCAIS], 
COUNT(*) AS [NUMERO DE NOTAS POR ANO] 
FROM [TABELA DE VENDEDORES] INNER JOIN
[NOTAS FISCAIS] ON [TABELA DE VENDEDORES].MATRICULA = [NOTAS FISCAIS].MATRICULA 
GROUP BY [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].NOME, YEAR([NOTAS FISCAIS].DATA) ORDER BY YEAR([NOTAS FISCAIS].DATA), [TABELA DE VENDEDORES].NOME

-- COMO FAZER JOIN NA OLD SCHOOL
SELECT * FROM [TABELA DE VENDEDORES], [NOTAS FISCAIS] WHERE [TABELA DE VENDEDORES].MATRICULA = [NOTAS FISCAIS].MATRICULA