SELECT * FROM [TABELA DE CLIENTES] ORDER BY [TABELA DE CLIENTES].NOME
SELECT * FROM [NOTAS FISCAIS] ORDER BY [NOTAS FISCAIS].CPF
SELECT * FROM [ITENS NOTAS FISCAIS]

-- INTERESSANTE DA FUNÇÃO JOIN COM UMA FUNÇÃO COUNT()
-- [TABELA DE CLIENTES].NOME, COUNT(*) SOZINHO CONTAR QUANTOS NOMES TEM NA TABELA DE CLIENTE MAS COM O INNER JOIN
-- ELE RETORNA DUAS TABELAS QUE O CPF SÃO IGUAL E SE TEM ALGUM CAMPO COM ESSES VALORES NULO ELE NÃO MONTA A TABELA RESULTANTE
-- ENTÃO NESSE CENARIO O INNER JOIN REPETE O NOME CASO O CPF SEJA IGUAL IDEPENDENTE DA QUANTIDADE DE CPF REPETIDO EM UMA DAS TABELAS
SELECT [TABELA DE CLIENTES].NOME, COUNT(*) AS [QUANTIDADE DE NOMES REPETIDOS] FROM [TABELA DE CLIENTES] INNER JOIN [NOTAS FISCAIS]
ON [TABELA DE CLIENTES].CPF = [NOTAS FISCAIS].CPF GROUP BY [TABELA DE CLIENTES].NOME

SELECT [NOTAS FISCAIS].CPF, COUNT(*) FROM [NOTAS FISCAIS] INNER JOIN [TABELA DE CLIENTES]
ON [NOTAS FISCAIS].CPF = [TABELA DE CLIENTES].CPF GROUP BY [NOTAS FISCAIS].CPF


SELECT * FROM [TABELA DE CLIENTES] INNER JOIN [NOTAS FISCAIS] ON
[TABELA DE CLIENTES].CPF = [NOTAS FISCAIS].CPF

--LEFT JOIN

SELECT [TABELA DE CLIENTES].NOME, COUNT(*) FROM [TABELA DE CLIENTES] LEFT JOIN
[NOTAS FISCAIS] ON [TABELA DE CLIENTES].CPF = [NOTAS FISCAIS].CPF GROUP BY [TABELA DE CLIENTES].NOME

