SELECT HORARIO , JUSTIFICATIVA , OBSERVACAO  FROM SZITEMPRESCRICAO  WHERE CODPRESCRICAO  = '252920'

SELECT SZPRD.IDPRD,

       TPRD.NOMEFANTASIA

FROM   SZPRD

       JOIN TPRD

         ON TPRD.CODCOLIGADA = SZPRD.CODCOLIGADA

            AND TPRD.IDPRD = SZPRD.IDPRD

WHERE  SZPRD.ANTIMICROBIANO = 'T'