SELECT * FROM [TABELA DE CLIENTES]
--SUN() SOMA OS VALORES PASSANDO O CAMPO DE REFERENCIA E O CAMPO A SER SOMADO
--MIN() ENCONTRA O MINIMO VALOR PELO PARAMETRO SELECT CAMPOREFERENCIA MIN(CAMPOVALOR)
--MAX() ENCONTRA O VALOR MAXIMO PASSADO PELO CRITERIO

SELECT ESTADO, MIN([LIMITE DE CREDITO]) AS [LIMITE MINIMO],
MAX([LIMITE DE CREDITO]) AS [LIMITE MAXIMO],
SUM([LIMITE DE CREDITO]) AS [SOMA DOS LIMITES EM RELACAO AO ESTADO] FROM [TABELA DE CLIENTES] GROUP BY ESTADO

SELECT * FROM [TABELA DE PRODUTOS]

--HAVING OPERADOR DE CONDICIONAIS
SELECT TAMANHO, MIN([PRECO DE LISTA]) AS [PRECO MINIMO],
MAX([PRECO DE LISTA]) AS [PRECO MAXIMO],
SUM([PRECO DE LISTA]) AS SOMA,
COUNT(*) AS [QUANDOS PRODUTOS DE CADA] FROM [TABELA DE PRODUTOS] GROUP BY TAMANHO HAVING SUM([PRECO DE LISTA]) > 50.000


