-- ORDER BY

SELECT * FROM [TABELA DE PRODUTOS]

-- ORDENA EM ORDEM CRESCENTE PELO UM CRITERIO QUE NO CASO E PRECO DE LISTA
SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [PRECO DE LISTA]
-- O DESC DIZ PARA O ORDER BY QUE A ORDEM E DECRECENTE
SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [PRECO DE LISTA] DESC

SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [NOME DO PRODUTO]

SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [NOME DO PRODUTO], TAMANHO, SABOR
-- DESC VALE SO PARA O CAMPO
SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [NOME DO PRODUTO] DESC, TAMANHO DESC, SABOR 


