SELECT SZPARECERPEP.CODCOLIGADA,
        		       SZPARECERPEP.CODPACIENTE,
        		       SZPARECERPEP.CODATENDIMENTO,
        		       SZPARECERPEP.SEQUENCIAL,
        		       SZPARECERPEP.CODPRESTSOLICITANTE,
        		       SZPRESTSOLICITANTE.RAZAOSOCIAL AS DESCPRESTSOLICITANTE,
        		       SZPARECERPEP.DATAHORA,
        		       SZPARECERPEP.JUSTIFICATIVA,
        		       SZPARECERPEP.CODESPECIALIDADE,
        		       SZESPECIALIDADE.DESCESPECGRUPO,
        		       SZPARECERPEP.CODPRESTSOLICITADO,
        		       SZPRESTSOLICITADO.RAZAOSOCIAL AS DESCPRESTSOLICITADO,
        		       SZPARECERPEP.DATAHORAPARECER,
        		       SZPARECERPEP.PENDENTE,
        		       SZPARECERPEP.CODPRESCRICAO,
        		       SZPARECERPEP.SEQUENCIALPARECER,
        		       SZPARECERPEP.STATUS,
                   SZUNIDATEND.IDUNIDATEND,
					         SZUNIDATEND.DESCRICAO AS DESCUNIDATEND,
                   SZPROCESSOASSINATURA.STATUS AS STATUSPROCESSO,
                   SZPROCESSOASSINATURA.CODIGO
        	    FROM SZPARECERPEP 
        INNER JOIN SZATENDIMENTO
                ON SZPARECERPEP.CODCOLIGADA = SZATENDIMENTO.CODCOLIGADA
        	     AND SZPARECERPEP.CODATENDIMENTO = SZATENDIMENTO.CODATENDIMENTO 
               AND SZPARECERPEP.CODPACIENTE =  SZATENDIMENTO.CODPACIENTE
		    INNER JOIN SZUNIDATEND 
			          ON SZATENDIMENTO.CODCOLIGADA = SZUNIDATEND.CODCOLIGADA
			         AND SZATENDIMENTO.IDUNIDATEND = SZUNIDATEND.IDUNIDATEND	
        INNER JOIN SZCADGERAL SZPRESTSOLICITANTE
                ON SZPARECERPEP.CODCOLIGADA = SZPRESTSOLICITANTE.CODCOLIGADA
        	     AND SZPARECERPEP.CODPRESTSOLICITANTE = SZPRESTSOLICITANTE.CODGERAL 
         LEFT JOIN SZCADGERAL SZPRESTSOLICITADO
                ON SZPARECERPEP.CODCOLIGADA = SZPRESTSOLICITADO.CODCOLIGADA
        	     AND SZPARECERPEP.CODPRESTSOLICITADO = SZPRESTSOLICITADO.CODGERAL 
         LEFT JOIN SZESPECIALIDADE 
                ON SZPARECERPEP.CODESPECIALIDADE = SZESPECIALIDADE.CODESPECGRUPO 
         LEFT JOIN SZPROCESSOASSINATURA 
                ON SZPROCESSOASSINATURA.CODIGO = SZPARECERPEP.CODIGOPROCESSO
             WHERE SZPARECERPEP.CODCOLIGADA = 1;