select * from [TABELA DE CLIENTES]

-- subconsultas
--SELECIONA NOME E BAIRRO NA TABELA DE CLIENTES ONDE O BAIRRO = BAIRRO DA TABELA DE VENDEDORES
select NOME, BAIRRO from [TABELA DE CLIENTES]
where BAIRRO IN(SELECT BAIRRO FROM [TABELA DE VENDEDORES])

SELECT * FROM [TABELA DE PRODUTOS]

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) [VALOR MAXIMO PRECO LISTA] FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT CPF, COUNT(*) FROM [NOTAS FISCAIS]
WHERE YEAR(DATA) = 2016
GROUP BY CPF
HAVING COUNT(*) > 2000