SELECT DISTINCT [TABELA DE CLIENTES].BAIRRO FROM [TABELA DE CLIENTES]
SELECT * FROM [TABELA DE CLIENTES]

SELECT DISTINCT [TABELA DE VENDEDORES].BAIRRO FROM [TABELA DE VENDEDORES]

-- O UNION TRAS TODOS OS BAIRROS DA TABELA CLIENTE E VENDEDORES SEM REPETIR A INFORMAÇÃO
SELECT DISTINCT [TABELA DE CLIENTES].BAIRRO FROM [TABELA DE CLIENTES]
UNION
SELECT DISTINCT [TABELA DE VENDEDORES].BAIRRO FROM [TABELA DE VENDEDORES]

-- TRAS TUDO DAS DUAS TABELA E INFORMAÇÕES QUE SE REPETEM EXEMPLO O BAIRRO SANTO AMARO TEM TANTO NA TABELA DE CLIENTES COMO
--NA TABELA DE VENDEDORES POR ESSE MOTIVO O DADO APARECE DUAS VEZES
SELECT DISTINCT [TABELA DE CLIENTES].BAIRRO FROM [TABELA DE CLIENTES]
UNION ALL
SELECT DISTINCT [TABELA DE VENDEDORES].BAIRRO FROM [TABELA DE VENDEDORES]

-- O UNION NÃO ACEITA CONSULTA DE DOIS CAMPOS DE TIPO DIFERENTE EXEMPLO

SELECT [TABELA DE CLIENTES].BAIRRO, [TABELA DE CLIENTES].[DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES]
UNION
SELECT [TABELA DE VENDEDORES].BAIRRO, [TABELA DE VENDEDORES].NOME FROM [TABELA DE VENDEDORES]

--NESSE EXEMPLO CAGADO ELE JUNTOU OS BAIRROS NAS DUAS TABELAS SEM REPETIR
-- OS BAIRRO QUE SAIU DA TABELA DE CLIENTE TROUXE A CIDADE E DA TABELA DE VENDEDORES TROUXE O NOME

SELECT [TABELA DE CLIENTES].BAIRRO, [TABELA DE CLIENTES].CIDADE FROM [TABELA DE CLIENTES]
UNION
SELECT [TABELA DE VENDEDORES].BAIRRO, [TABELA DE VENDEDORES].NOME FROM [TABELA DE VENDEDORES]


SELECT [TABELA DE CLIENTES].BAIRRO, [TABELA DE CLIENTES].NOME,'CLIENTES' FROM [TABELA DE CLIENTES]
UNION
SELECT [TABELA DE VENDEDORES].BAIRRO, [TABELA DE VENDEDORES].NOME, 'VENDEDORES' FROM [TABELA DE VENDEDORES]